### ISSUE TITLE
Multi-blind scrambling display

### ISSUE THREAD

**Issue by Sixstringcal** [cubing/scramble-table#1]
Proposed flow (assumption: the scrambler is already set):

If the event is 333mbf, also take in a value for number of cubes attempted.

Outline the WCA legal shape of the cubes to be scrambled for that input (ie closest to a square), but grayed out.  Show scramble 1 at that time.

Allow a input that advances the multiblind scramble.  When this happens, it should advance the next scramble, and add the U face of the scramble to the grayed out shape.  This ideally should fill out left to right, then top to bottom.

Once all cubes have been scrambled, it should show the layout of all the U faces.  The user should be able to click on any of them and be shown the correct scramble for it, along with the scramble image.

At any point during the scrambling process, the scrambler should be able to go back and see a previous scramble in case they messed something up.  Ideally there should be a resume button, which should take you back to where you were.  It should also be visibly obvious you are looking at a previous scramble and not the current one when you are looking at a previous scramble.

**Comment by lgarron** [comment]
This has been implemented since v0.1.0: https://github.com/cubing/scramble-table/releases/tag/v0.1.0
