### ISSUE TITLE
Allow clearing the current scramble per scrambler

### ISSUE THREAD

**Issue by Sixstringcal** [cubing/scramble-table#5]
Currently, the only way to clear a scramble for a scrambler to load up a new scramble is to markAsSigned().

A few scenarios could lead to the use case where a scrambler should be able to clear out who they are scrambling for that don't involve signing anything:
- They misscrambled and someone else will be solving it while they scramble a new cube
- They put the wrong cube in to be scrambled and actually need to scramble a different cube

**Comment by lgarron** [comment]
Alright, please try `v0.2.2` and see if it meets your needs! 😄

**Comment by lgarron** [comment]
I've also added https://github.com/cubing/scramble-table/commit/2cc183f5c29baf1567e67c73e292adcdcd529b8a per chat feedback. Closing this out as implemented; please let me know if you need any additional changes!
